services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=pmapp'
      - 'MYSQL_PASSWORD=ThePassword'
      - 'MYSQL_ROOT_PASSWORD=ThePassword'
    ports:
      - '3306'
    volumes:
    - ./mysql:/var/lib/mysql
  
  elasticsearch:
    image: elasticsearch:8.8.0
    container_name: elasticsearch
    ports:
        - "9200:9200"
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      # Since ES 8, SSL is on by default, disabling on local
      - xpack.security.enabled=false
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data