services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=pmapp'
      - 'MYSQL_PASSWORD=ThePassword'
      - 'MYSQL_ROOT_PASSWORD=ThePassword'
    ports:
      - '3306'
    volumes:
    - ./mysql:/var/lib/mysql
